Repository tofu-tf/tofu, pull requests merged in 2019-12, with the labels that each got.

#75 Added Release Drafter app to collect release notes
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#76 Minor changes to the release notes template
  .github/release-drafter.yml
Labels: skip-changelog

#77 Update magnolia to 0.12.5
  project/Dependencies.scala
Labels: chore

#43 Add mode to @masked annotation
  logging/derivation/src/main/scala/tofu/logging/derivation/annotations.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/loggable.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/masking.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/package.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/show.scala
Labels: enhancement

#83 Add logos by @impurepics
  README.md
  logos/tofu-logo.png
  logos/tofu-mascot.png
  website/static/img/favicon.ico
Labels: enhancement

#85 Make ServiceLogging invariant
  logging/structured/src/main/scala/tofu/logging/Logging.scala
Labels: breaking-change

#91 Update sbt to 1.3.6
  project/build.properties
Labels: chore

#90 Update tethys-core, tethys-jackson to 0.11.0
  project/Dependencies.scala
Labels: chore

#88 add specialized operations to construct loggers by class tags and names
  build.sbt
  logging/structured/src/main/scala-2.12/tofu/logging/LogsVOps.scala
  logging/structured/src/main/scala-2.13/tofu/logging/LogsVOps.scala
  logging/structured/src/main/scala/tofu/logging/Logs.scala
Labels: enhancement, logging
