Repository tofu-tf/tofu, pull requests merged in 2020-01, with the labels that each got.

#101 Update magnolia to 0.12.6
  project/Dependencies.scala
Labels: chore

#100 Add summon to Execute, add putErr and putErrLn to Console, scalafmt f…
  concurrent/src/main/scala/tofu/concurrent/Atom.scala
  concurrent/src/main/scala/tofu/concurrent/QVar.scala
  core/src/main/scala/tofu/Execute.scala
  core/src/main/scala/tofu/common/Console.scala
  higherKindCore/src/main/scala/tofu/syntax/monadic.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/loggable.scala
  logging/structured/src/main/scala-2.12/tofu/logging/LogsVOps.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
Labels: enhancement

#99 Update enumeratum to 1.5.15
  project/Dependencies.scala
Labels: chore

#105 Update monocle-core to 2.0.1
  project/Dependencies.scala
Labels: chore

#111 Fix hiding order dependency in Loggable
  logging/structured/src/main/scala/tofu/logging/impl/ContramapLoggable.scala
  logging/structured/src/main/scala/tofu/logging/impl/HiddenLoggable.scala
  logging/structured/src/test/scala/tofu/logging/LoggableSuite.scala
Labels: fix

#114 Require at least `ContravariantRaise` instance for `raise` syntax.
  core/src/main/scala/tofu/syntax/error.scala
Labels: fix

#106 Remove inlining options in build file
  build.sbt
Labels: chore

#119 Update cats-tagless-macros to 0.11
  project/Dependencies.scala
Labels: chore

#118 Fix wrong type of Finally instance derived from Bracket
  core/src/main/scala/tofu/Guarantee.scala
  core/src/test/scala/tofu/GuaranteeSuite.scala
Labels: fix

#115 fix ZLogs
  zio/logging/src/main/scala/tofu/logging/zio/ZLogs.scala
  zio/logging/src/main/scala/tofu/logging/zio/impl/UIOZLogging.scala
  zio/logging/src/main/scala/tofu/logging/zio/impl/URIOZLoggingImpl.scala
  zio/logging/src/main/scala/tofu/logging/zio/package.scala
Labels: fix

#124 fix logging zio shadowing
  zio/logging/src/main/scala/tofu/logging/zlogs/ZLogs.scala
  zio/logging/src/main/scala/tofu/logging/zlogs/impl/UIOZLogging.scala
  zio/logging/src/main/scala/tofu/logging/zlogs/impl/URIOZLoggingImpl.scala
  zio/logging/src/main/scala/tofu/logging/zlogs/package.scala
Labels: fix

#125 Add new metals file to .gitignore
  .gitignore
Labels: chore

#130 Add HasContext docs
  docs/hascontext.md
Labels: chore
