Repository tofu-tf/tofu, pull requests merged in 2020-12, with the labels that each got.

#472 Update refined to 0.9.19
  project/Dependencies.scala
Labels: chore

#474 Update sbt to 1.4.5
  project/build.properties
Labels: chore

#473 Support for `WithContext` structure promotion added to `Context.Companion`
  core/src/main/scala/tofu/Context.scala
  core/src/test/scala/tofu/ContextSuite.scala
Labels: fix

#469 `ContravariantRaise` undeprecated.
  core/src/main/scala/tofu/Errors.scala
Labels: fix

#465 Deprecate Unlift[F, G].effect and others
  core/src/main/scala/tofu/syntax/unlift.scala
  core/src/test/scala/tofu/syntax/UnliftSuite.scala
Labels: fix

#464 Update Scala version
  .github/workflows/scala.yml
  build.sbt
  concurrent/src/main/scala/tofu/concurrent/ReadWrite.scala
  optics/core/src/test/scala/tofu/optics/core/ChainSuite.scala
  src/test/scala/tofu/concurrent/ContextTRebaseSuite.scala
Labels: chore

#462 Fix instances for layered ZIO
  build.sbt
  zio/core/src/main/scala/tofu/zioInstances/ZioInstances.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
  zio/core/src/main/scala/tofu/zioInstances/implicits.scala
  zio/core/src/test/scala/tofu/zioInstances/ZioInstancesSuite.scala
Labels: fix

#478 Add `tofu-logging-log4cats` module
  README.md
Labels: docs

#480 Update fs2-io to 2.5.0
  project/Dependencies.scala
Labels: chore

#479 Update scala-collection-compat to 2.3.2
  project/Dependencies.scala
Labels: chore

#481 Update sbt to 1.4.6
  project/build.properties
Labels: chore

#482 Update derevo-cats-tagless, derevo-core to 0.11.6
  project/Dependencies.scala
Labels: chore
