Repository tofu-tf/tofu, pull requests merged in 2020-03, with the labels that each got.

#178 Update magnolia to 0.12.8
  project/Dependencies.scala
Labels: chore

#175 Yet another F[Option[A]] syntax
  core/src/main/scala/tofu/syntax/foption.scala
  core/src/test/scala/tofu/syntax/FOptionSuite.scala
Labels: enhancement

#176 Refactoring the feither syntax, add widen methods for Either[E, A]
  core/src/main/scala/tofu/syntax/either.scala
  core/src/main/scala/tofu/syntax/feither.scala
Labels: enhancement

#173 Minimal documentation for `optics` module
  docs/optics-hierarchy.png
  docs/optics.md
  website/sidebars.json
Labels: docs

#182 Upgrade to zio 1.0.0-RC18-1
  project/Dependencies.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuConcurrentInstance.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
Labels: chore

#184 Specialized version of startAndForget and subcontext Unlift
  env/src/main/scala/tofu/env/EnvFunctorstance.scala
  env/src/main/scala/tofu/env/EnvInstances.scala
  env/src/main/scala/tofu/env/EnvUnliftTask.scala
Labels: enhancement

#185 Update zio-interop-cats to 2.0.0.0-RC11
  project/Dependencies.scala
Labels: chore

#172 Add Agent docs
  concurrent/src/main/scala/tofu/concurrent/Agent.scala
  docs/agent.md
  website/sidebars.json
Labels: docs

#177 Created documentation for tofu.common.Console
  core/src/main/scala/tofu/common/Console.scala
  core/src/main/scala/tofu/syntax/console.scala
  docs/console.md
  website/sidebars.json
Labels: docs

#189 Update monocle-core to 2.0.4
  project/Dependencies.scala
Labels: chore

#188 Provide and HasProvide
  core/src/main/scala/tofu/Context.scala
  core/src/main/scala/tofu/package.scala
Labels: enhancement

#186 Promotion of lenses of marked inner fields on classy lenses generation
  optics/macro/src/main/scala/tofu/optics/macros/Optics.scala
  optics/macro/src/main/scala/tofu/optics/macros/promote.scala
  optics/macro/src/test/scala-2.13/tofu/optics/macros/TestClassyContains.scala
  optics/macro/src/test/scala/tofu/optics/macros/GenContainsSpec.scala
  optics/macro/src/test/scala/tofu/optics/macros/GenEquivalentSpec.scala
  optics/macro/src/test/scala/tofu/optics/macros/GenSubsetSpec.scala
  optics/macro/src/test/scala/tofu/optics/macros/TestDomain.scala
Labels: enhancement

#195 Fix zio interop instances and implicits
  optics/core/src/main/scala/tofu/optics/functions.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
  zio/core/src/main/scala/tofu/zioInstances/implicits.scala
  zio/core/src/main/scala/tofu/zioInstances/package.scala
  zio/core/src/test/scala/tofu/zioInstances/ZioInstancesSuit.scala
Labels: fix

#198 Update zio-interop-cats to 2.0.0.0-RC12
  project/Dependencies.scala
Labels: chore

#197 Update zio to 1.0.0-RC18-2
  project/Dependencies.scala
Labels: chore

#196 move Context summoners to the appropriate source
  core/src/main/scala/tofu/Context.scala
  core/src/main/scala/tofu/Errors.scala
Labels: chore, fix

#199 Fix mvar-base logs caching
  logging/structured/src/main/scala/tofu/logging/impl/CachedLogs.scala
Labels: fix

#200 Make new multiparameter typeclasses for contexts, simplifying implicit search
  concurrent/src/main/scala/tofu/concurrent/ContextT.scala
  concurrent/src/main/scala/tofu/concurrent/impl/contextt.scala
  concurrent/src/test/scala/tofu/concurrent/ContextTSummonCheck.scala
  core/src/main/scala/tofu/Context.scala
  core/src/test/scala/tofu/ContextSuite.scala
  env/src/main/scala/tofu/env/EnvFunctorstance.scala
Labels: enhancement, fix

#164 Add logging documentation
  docs/logging.md
  logging/structured/src/main/scala/tofu/logging/Logs.scala
  website/sidebars.json
Labels: docs

#205 Reduce warnings
  build.sbt
  concurrent/src/main/scala/tofu/concurrent/ContextT.scala
  concurrent/src/main/scala/tofu/concurrent/impl/contextt.scala
  concurrent/src/test/scala/tofu/concurrent/ReadWriteTests.scala
  config/src/test/scala/tofu/config/ConfigSuite.scala
  core/src/main/scala/tofu/lift/Unlift.scala
  core/src/test/scala/tofu/syntax/FEitherSuite.scala
  core/src/test/scala/tofu/syntax/FoldableSuite.scala
  data/src/test/scala/tofu/data/FluxSuite.scala
  derivation/src/test/scala/tofu/data/derived/MergeSuite.scala
  derivation/src/test/scala/tofu/higherKind/derived/RepresentableKSuite.scala
  env/src/main/scala/tofu/env/Env.scala
  env/src/main/scala/tofu/env/EnvFunctions.scala
  env/src/test/scala/tofu/env/EnvSuite.scala
  env/src/test/scala/tofu/env/EnvTraverseSuite.scala
  env/src/test/scala/tofu/env/ParEnvSuite.scala
  higherKindCore/src/main/scala/tofu/higherKind/RepresentableK.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
  higherKindCore/src/main/scala/tofu/syntax/functionK.scala
  logging/derivation/src/test/scala/tofu/logging/derivation/DerivedLoggableSuite.scala
  logging/structured/src/main/scala/tofu/logging/Logging.scala
  logging/structured/src/main/scala/tofu/logging/TethysBuilder.scala
  logging/structured/src/test/scala/tofu/logging/LoggableSuite.scala
  observable/src/test/scala/tofu/observable/TakeWhileInclusiveSuite.scala
  optics/core/src/main/scala/tofu/optics/Same.scala
  optics/core/src/test/scala/tofu/optics/core/ChainSuite.scala
  optics/macro/src/main/scala/tofu/optics/macros/Optics.scala
Labels: chore, fix

#208 Update fs2-io to 2.3.0
  project/Dependencies.scala
Labels: chore

#207 Fix implicit hiding for Mid
  higherKindCore/src/main/scala/tofu/higherKind/Mid.scala
  higherKindCore/src/main/scala/tofu/higherKind/Post.scala
  higherKindCore/src/main/scala/tofu/higherKind/Pre.scala
  higherKindCore/src/test/scala/tofu/higherKind/MidSuite.scala
Labels: fix
