Repository tofu-tf/tofu, pull requests merged in 2020-11, with the labels that each got.

#436 Integration with log4cats
  build.sbt
  docs/logging.md
  logging/interop/log4cats/src/main/scala/tofu/logging/log4cats/package.scala
  project/Dependencies.scala
Labels: enhancement

#434 A shortcut for ZIO WIthLocal instance definition
  zio/core/src/main/scala/tofu/zioInstances/ZioInstances.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
Labels: enhancement, hacktoberfest

#435 Added new syntax and type alias for ExceptT
  core/src/main/scala/tofu/syntax/feither.scala
  core/src/main/scala/tofu/syntax/foption.scala
  data/src/main/scala/tofu/data/Embedded.scala
  data/src/main/scala/tofu/data/data.scala
  higherKindCore/src/main/scala/tofu/syntax/monadic.scala
Labels: enhancement

#416 Add Mid documentation
  docs/mid.md
  website/sidebars.json
Labels: docs, hacktoberfest

#414 Scaladoc for Context.scala
  core/src/main/scala/tofu/Context.scala
Labels: docs, hacktoberfest

#425 [WIP] Logging Layout and Marker context integration with Scribe
  build.sbt
  logging/scribe/src/main/scala/org/slf4j/impl/StaticLoggerBinder.scala
  logging/scribe/src/main/scala/org/slf4j/impl/StaticMDCBinder.scala
  logging/scribe/src/main/scala/org/slf4j/impl/StaticMarkerBinder.scala
  logging/scribe/src/main/scala/tofu/logging/ELKFormatter.scala
  logging/scribe/src/main/scala/tofu/logging/scribe/RecordLoggable.scala
  logging/scribe/src/main/scala/tofu/logging/scribe/internal/MarkedOutput.scala
  logging/scribe/src/main/scala/tofu/logging/scribe/internal/ScribeLoggerAdapter.scala
  project/Dependencies.scala
Labels: wip

#432 Interop with cats mtl
  README.md
  build.sbt
  core/interop/cats-mtl/src/main/scala/tofu/core/interop/catsmtl/CatsMTLTofuInstances.scala
  core/interop/cats-mtl/src/main/scala/tofu/core/interop/catsmtl/TofuCatsMTLInstances.scala
  core/interop/cats-mtl/src/main/scala/tofu/core/interop/catsmtl/instances.scala
  core/interop/cats-mtl/src/main/scala/tofu/core/interop/catsmtl/mtlimplicits.scala
  core/interop/cats-mtl/src/main/scala/tofu/core/interop/catsmtl/tofuimplicits.scala
  core/interop/cats-mtl/src/test/scala/tofu/core/interop/catsmtl/CatsMtlFromTofuSummonChecks.scala
  core/interop/cats-mtl/src/test/scala/tofu/core/interop/catsmtl/TofuCatsMtlExplicitChecks.scala
  core/interop/cats-mtl/src/test/scala/tofu/core/interop/catsmtl/TofuFromCatsMtlSummonChecks.scala
  docs/cats-mtl-interop.md
  project/Dependencies.scala
  website/sidebars.json
Labels: enhancement

#443 Update fs2-io to 2.4.5
  project/Dependencies.scala
Labels: chore

#441 Update monix to 3.3.0
  project/Dependencies.scala
Labels: chore

#442 Update scalatest to 3.2.3
  project/Dependencies.scala
Labels: chore

#449 Update sbt to 1.4.3
  project/build.properties
Labels: chore

#454 Update scala-collection-compat to 2.3.0
  project/Dependencies.scala
Labels: chore

#453 Update kind-projector to 0.11.1
  project/Dependencies.scala
Labels: chore

#448 Update refined to 0.9.18
  project/Dependencies.scala
Labels: chore

#457 Update fs2-io to 2.4.6
  project/Dependencies.scala
Labels: chore

#456 Update sbt to 1.4.4
  project/build.properties
Labels: chore

#458 Update doobie-core to 0.9.4
  project/Dependencies.scala
Labels: chore

#459 Update scala-collection-compat to 2.3.1
  project/Dependencies.scala
Labels: chore

#468 Update cats-effect to 2.3.0
  project/Dependencies.scala
Labels: chore

#466 Update cats-mtl to 1.1.0
  project/Dependencies.scala
Labels: chore

#467 Summoners for streams type classes
  streams/src/main/scala/tofu/streams/Broadcast.scala
  streams/src/main/scala/tofu/streams/Chunks.scala
  streams/src/main/scala/tofu/streams/Compile.scala
  streams/src/main/scala/tofu/streams/Emits.scala
  streams/src/main/scala/tofu/streams/Merge.scala
  streams/src/main/scala/tofu/streams/Pace.scala
  streams/src/main/scala/tofu/streams/ParFlatten.scala
  streams/src/main/scala/tofu/streams/Region.scala
  streams/src/main/scala/tofu/streams/Temporal.scala
Labels: enhancement

#470 Update kind-projector to 0.11.2
  project/Dependencies.scala
Labels: chore
