Repository tofu-tf/tofu, pull requests merged in 2020-06, with the labels that each got.

#297 Add new loggable instances
  logging/structured/src/main/scala/tofu/logging/Loggable.scala
Labels: enhancement

#298 errorCause logs full stacktrace with cause and suppressed
  logging/structured/src/main/scala/tofu/logging/Loggable.scala
Labels: fix

#296 Add logging interop modules to build.sbt properly
  build.sbt
Labels: chore

#294 Many fixes in README.md
  README.md
Labels: docs

#291 LocalOps alternative
  core/src/main/scala/tofu/syntax/context.scala
Labels: enhancement

#279 Bracket mvar opts agent behaviour
  core/src/main/scala/tofu/syntax/bracket.scala
  memo/src/main/scala/tofu/memo/CacheKeyState.scala
  memo/src/main/scala/tofu/memo/CacheState.scala
Labels: enhancement, fix

#312 Update monocle-core to 2.0.5
  project/Dependencies.scala
Labels: chore

#313 New Unlift zio for partial Has-context
  zio/core/src/main/scala/tofu/zioInstances/ZioInstances.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
  zio/core/src/main/scala/tofu/zioInstances/implicits.scala
Labels: enhancement

#305 Kind enumeration description
  docs/internal/kind-enumeration.md
  docs/internal/variance-enumeration.md
Labels: docs

#320 Update scalatest to 3.2.0
  project/Dependencies.scala
Labels: chore

#319 Add reRaise and adaptError methods
  core/src/main/scala/tofu/Errors.scala
  core/src/main/scala/tofu/syntax/error.scala
  core/src/main/scala/tofu/syntax/feither.scala
  core/src/test/scala/tofu/ErrorsSuite.scala
Labels: enhancement

#323 Update zio to 1.0.0-RC21
  project/Dependencies.scala
Labels: chore

#310 Bifunctor Starter pack
  .gitignore
  build.sbt
  core/src/main/scala/tofu/Void.scala
  core/src/main/scala/tofu/bi/BiContext.scala
  core/src/main/scala/tofu/bi/lift/BiLift.scala
  core/src/main/scala/tofu/bi/package.scala
  core/src/main/scala/tofu/package.scala
  core/src/main/scala/tofu/syntax/bracket.scala
  core/src/main/scala/tofu/syntax/feither.scala
  data/src/main/scala/tofu/data/Calc.scala
  data/src/main/scala/tofu/data/calc/CalcM.scala
  data/src/main/scala/tofu/data/calc/CalcMInstances.scala
  data/src/main/scala/tofu/data/calc/CalcMOps.scala
  data/src/main/scala/tofu/data/calc/CalcRunner.scala
  data/src/main/scala/tofu/data/calc/CalcT.scala
  data/src/main/scala/tofu/data/calc/Continue.scala
  data/src/main/scala/tofu/data/calc/StepResult.scala
  data/src/main/scala/tofu/data/calc/Translator.scala
  data/src/main/scala/tofu/data/data.scala
  data/src/test/scala/tofu/data/CalcSuite.scala
  derivation/src/main/scala/tofu/higherKind/derived/derived.scala
  derivation/src/test/scala/tofu/higherKind/derived/EmbedKSuite.scala
  derivation/src/test/scala/tofu/higherKind/derived/EmbedSuite.scala
  derivation/src/test/scala/tofu/higherKind/derived/RepresentableKSuite.scala
  docs/internal/bimonad.md
  docs/internal/kind-enumeration.md
  env/src/main/scala/tofu/env/bio/EnvBio.scala
  env/src/main/scala/tofu/env/bio/EnvBioFunctions.scala
  env/src/main/scala/tofu/env/bio/EnvBioInstances.scala
  env/src/main/scala/tofu/env/bio/EnvBioSpecializedFunctions.scala
  env/src/main/scala/tofu/env/bio/package.scala
  env/src/test/scala/tofu/env/bio/EnvBioSuite.scala
  higherKindCore/src/main/scala-2.12/tofu/compat/package.scala
  higherKindCore/src/main/scala-2.13/tofu/compat/package.scala
  higherKindCore/src/main/scala/tofu/control/Bind.scala
  higherKindCore/src/main/scala/tofu/control/impl/BindInstanceChain.scala
  higherKindCore/src/main/scala/tofu/higherKind/MonoidalK.scala
  higherKindCore/src/main/scala/tofu/higherKind/PureK.scala
  higherKindCore/src/main/scala/tofu/higherKind/RepresentableK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/BiPoint.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/BiRepresentableK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/EmbedBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/Fun2BK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/FunBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/FunctorBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/MonoidalBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/PureBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/RepBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/SemigroupalBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/Tuple2BK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/package.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/derived.scala
  higherKindCore/src/main/scala/tofu/syntax/bind.scala
  optics/core/src/main/scala/tofu/optics/Subset.scala
  optics/core/src/main/scala/tofu/optics/functions/CollectionFunctions.scala
Labels: enhancement
