Repository tofu-tf/tofu, pull requests merged in 2020-08, with the labels that each got.

#349 Strict lints, scalac upgrade, add sbt-rewarn
  .github/workflows/scala.yml
  .travis.yml
  build.sbt
  concurrent/src/test/scala/tofu/concurrent/DaemonTests.scala
  concurrent/src/test/scala/tofu/concurrent/ReadWriteTests.scala
  core/src/main/scala/tofu/Fire.scala
  core/src/main/scala/tofu/alias/Do.scala
  core/src/main/scala/tofu/internal/NonTofu.scala
  core/src/main/scala/tofu/streaming.scala
  core/src/main/scala/tofu/syntax/consume.scala
  core/src/main/scala/tofu/syntax/lift.scala
  data/src/main/scala/tofu/data/Calc.scala
  data/src/main/scala/tofu/data/calc/CalcM.scala
  data/src/main/scala/tofu/data/data.scala
  data/src/test/scala/tofu/data/CalcSuite.scala
  derivation/src/test/scala/tofu/higherKind/derived/EmbedSuite.scala
  derivation/src/test/scala/tofu/higherKind/derived/RepresentableKVarArgSuite.scala
  doobie/src/test/scala/tofu/doobie/DoobieInstancesSuite.scala
  higherKindCore/src/main/scala-2.12/tofu/compat/package.scala
  higherKindCore/src/main/scala-2.13/tofu/compat/package.scala
  higherKindCore/src/main/scala/tofu/control/Bind.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/BiRepresentableK.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
  logging/structured/src/main/scala/tofu/logging/Logging.scala
  logging/structured/src/main/scala/tofu/logging/Logs.scala
  logging/structured/src/main/scala/tofu/logging/TethysBuilder.scala
  optics/core/src/main/scala/tofu/optics/Same.scala
  optics/core/src/main/scala/tofu/optics/Upcast.scala
  optics/core/src/main/scala/tofu/optics/Update.scala
  optics/core/src/test/scala/tofu/optics/core/ChainSuite.scala
  optics/macro/src/main/scala/tofu/optics/macros/Optics.scala
  project/plugins.sbt
Labels: chore

#350 Update scalatest to 3.2.1
  project/Dependencies.scala
Labels: chore

#351 Add Lift instances via IsoK, UnliftIO instance for ReaderT
  core/src/main/scala/tofu/lift/Unlift.scala
  core/src/test/scala/tofu/lift/UnliftSuite.scala
Labels: enhancement

#352 IsoK summon method
  core/src/main/scala/tofu/lift/IsoK.scala
Labels: enhancement

#355 Print full stacktrace in ELKLayout
  logging/layout/src/main/scala/tofu/logging/logback/IEventLoggable.scala
Labels: enhancement, logging

#353 Make started fibers interruptible in zio-interop
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuConcurrentInstance.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
Labels: fix

#358 Update monocle-core to 2.1.0
  project/Dependencies.scala
Labels: chore

#357 Additional instances for ContextT and others
  build.sbt
  concurrent/src/main/scala/tofu/concurrent/Atom.scala
  concurrent/src/main/scala/tofu/concurrent/ContextT.scala
  concurrent/src/main/scala/tofu/concurrent/impl/contextt.scala
  core/src/main/scala/tofu/Errors.scala
  core/src/main/scala/tofu/control/impl/SelectiveInstances.scala
  core/src/main/scala/tofu/lift/Rebase.scala
  core/src/main/scala/tofu/syntax/selective.scala
  core/src/test/scala/tofu/syntax/RetrySuite.scala
  data/src/main/scala/tofu/data/calc/CalcMOps.scala
  data/src/main/scala/tofu/data/calc/CalcRunner.scala
  data/src/main/scala/tofu/data/data.scala
  higherKindCore/src/main/scala-2.12/tofu/compat/package.scala
  higherKindCore/src/main/scala-2.13/tofu/compat/package.scala
  higherKindCore/src/main/scala/tofu/syntax/monadic.scala
  src/test/scala/tofu/concurrent/ContextTRebaseSuite.scala
Labels: enhancement, fix

#360 Update fs2-io to 2.4.3
  project/Dependencies.scala
Labels: chore

#362 Errors hierarchy fix. Remove subtype instance adapting from cats
  core/src/main/scala/tofu/Errors.scala
  core/src/main/scala/tofu/errorInstances/package.scala
  core/src/main/scala/tofu/internal/NonTofu.scala
  zio/core/src/test/scala/tofu/zioInstances/ZioInstancesSuite.scala
Labels: fix

#366 Update fs2-io to 2.4.4
  project/Dependencies.scala
Labels: chore

#365 Update scalatest to 3.2.2
  project/Dependencies.scala
Labels: chore

#363 Update zio to 1.0.1
  project/Dependencies.scala
Labels: chore
