Repository tofu-tf/tofu, pull requests merged in 2020-02, with the labels that each got.

#135 Update sbt to 1.3.8
  project/build.properties
Labels: chore

#132 Update Selective typeclass and instances
  core/src/main/scala/tofu/control/Selective.scala
  core/src/main/scala/tofu/control/impl/ApplicativeDelegate.scala
  core/src/main/scala/tofu/control/impl/ApplyDelegate.scala
  core/src/main/scala/tofu/control/impl/FunctorDelegate.scala
  core/src/main/scala/tofu/control/impl/SelectiveInstances.scala
  core/src/main/scala/tofu/syntax/either.scala
  core/src/main/scala/tofu/syntax/selective.scala
  higherKindCore/src/main/scala/tofu/syntax/monadic.scala
Labels: enhancement

#131 Add ZIO random and console instances, add implicit instance container…
  .travis.yml
  build.sbt
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
  zio/core/src/main/scala/tofu/zioInstances/implicits.scala
  zio/core/src/main/scala/tofu/zioInstances/package.scala
Labels: enhancement

#110 Solution to #109
  core/src/main/scala/tofu/Errors.scala
  core/src/main/scala/tofu/package.scala
Labels: enhancement

#153 Update fs2-io to 2.2.2
  project/Dependencies.scala
Labels: chore

#157 Update scalafmt to 2.4.1
  .scalafmt.conf
  derivation/src/main/scala/tofu/data/derived/Merge.scala
  env/src/main/scala/tofu/env/Env.scala
  logging/structured/src/main/scala/tofu/logging/LogRenderer.scala
  logging/structured/src/main/scala/tofu/logging/LogTree.scala
  optics/macro/src/main/scala/tofu/optics/macros/Optics.scala
Labels: chore

#158 Update silencer-lib, silencer-plugin to 1.5.0
  project/Dependencies.scala
Labels: chore

#161 Fix Selective instance priority
  core/src/main/scala/tofu/control/Selective.scala
  core/src/test/scala/tofu/control/SelectiveSummon.scala
Labels: fix

#171 Update alleycats-core, cats-core, cats-free to 2.1.1
  project/Dependencies.scala
Labels: chore

#170 Update magnolia to 0.12.7
  project/Dependencies.scala
Labels: chore

#169 Add convenient syntax for working with F[Either[E, A]]
  core/src/main/scala/tofu/syntax/feither.scala
  core/src/test/scala/tofu/syntax/FEitherSuite.scala
Labels: enhancement

#166 Update scalafmt-core to 2.4.2
  .scalafmt.conf
Labels: chore

#162 Add convenient syntax for working with F[Option[A]]
  core/src/main/scala/tofu/syntax/foption.scala
  core/src/test/scala/tofu/syntax/FOptionSuite.scala
Labels: enhancement

#165 Add MakeRef documentation
  concurrent/src/main/scala/tofu/concurrent/MakeRef.scala
  docs/concurrent-makeref.md
  website/sidebars.json
Labels: docs
