Repository tofu-tf/tofu, pull requests merged in 2020-10, with the labels that each got.

#403 Update zio-interop-cats to 2.1.4.1
  project/Dependencies.scala
Labels: chore

#407 Update zio to 1.0.2
  project/Dependencies.scala
Labels: chore

#410 Update sbt, sbt-rewarn, scalafmt
  .scalafmt.conf
  concurrent/src/main/scala/tofu/concurrent/Agent.scala
  concurrent/src/main/scala/tofu/concurrent/Atom.scala
  concurrent/src/main/scala/tofu/concurrent/Gatekeeper.scala
  concurrent/src/main/scala/tofu/concurrent/MakeRef.scala
  concurrent/src/main/scala/tofu/concurrent/QVar.scala
  concurrent/src/main/scala/tofu/concurrent/ReadWrite.scala
  core/src/main/scala/tofu/Errors.scala
  core/src/main/scala/tofu/Init.scala
  core/src/main/scala/tofu/bi/BiContext.scala
  core/src/main/scala/tofu/common/time.scala
  core/src/main/scala/tofu/lift/Unlift.scala
  core/src/main/scala/tofu/syntax/bracket.scala
  core/src/main/scala/tofu/syntax/foldable.scala
  core/src/main/scala/tofu/syntax/time.scala
  doobie/src/main/scala/tofu/doobie/log/EmbeddableLogHandler.scala
  doobie/src/main/scala/tofu/doobie/log/LogHandlerF.scala
  doobie/src/main/scala/tofu/doobie/transactor/Txr.scala
  env/src/main/scala/tofu/env/bio/EnvBioFunctions.scala
  higherKindCore/src/main/scala/tofu/higherKind/MonoidalK.scala
  higherKindCore/src/main/scala/tofu/higherKind/Point.scala
  higherKindCore/src/main/scala/tofu/higherKind/Post.scala
  higherKindCore/src/main/scala/tofu/higherKind/Pre.scala
  higherKindCore/src/main/scala/tofu/higherKind/PureK.scala
  logging/structured/src/main/scala/tofu/logging/LogRenderer.scala
  logging/structured/src/main/scala/tofu/logging/Loggable.scala
  logging/structured/src/main/scala/tofu/logging/Logs.scala
  optics/core/src/main/scala/tofu/optics/package.scala
  optics/macro/src/main/scala/tofu/optics/macros/GenEquivalent.scala
  project/build.properties
  project/plugins.sbt
Labels: chore

#422 Add summon objects for Scoped aliases
  core/src/main/scala/tofu/Scoped.scala
  core/src/main/scala/tofu/package.scala
  doobie/src/main/scala/tofu/doobie/log/EmbeddableLogHandler.scala
Labels: fix, hacktoberfest

#427 Update cats-tagless-macros to 0.12
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
  project/Dependencies.scala
Labels: chore

#426 Update simulacrum to 1.0.1
  core/src/main/scala/tofu/Fire.scala
  core/src/main/scala/tofu/Timeout.scala
  core/src/main/scala/tofu/common/Console.scala
  core/src/main/scala/tofu/control/Consume.scala
  core/src/main/scala/tofu/control/ContravariantFilter.scala
  core/src/main/scala/tofu/control/Optional.scala
  core/src/main/scala/tofu/control/Partial.scala
  core/src/main/scala/tofu/control/Selective.scala
  core/src/main/scala/tofu/control/Switch.scala
  core/src/main/scala/tofu/generate/GenRandom.scala
  core/src/main/scala/tofu/generate/GenUUID.scala
  derivation/src/main/scala/tofu/data/derived/Merge.scala
  higherKindCore/src/main/scala/tofu/higherKind/Embed.scala
  higherKindCore/src/main/scala/tofu/higherKind/MonoidalK.scala
  higherKindCore/src/main/scala/tofu/higherKind/PureK.scala
  higherKindCore/src/main/scala/tofu/higherKind/RepresentableK.scala
  logging/structured/src/main/scala/tofu/logging/Loggable.scala
  memo/src/main/scala/tofu/memo/Memoize.scala
  project/Dependencies.scala
  src/test/scala/tofu/concurrent/ContextTRebaseSuite.scala
Labels: chore

#417 Tofu Streams documentation
  docs/streams.md
  website/sidebars.json
Labels: hacktoberfest

#428 Fix zio executor retrieving for blocking
  .gitignore
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
Labels: fix, hacktoberfest

#430 Update typesafe:config to 1.4.1
  project/Dependencies.scala
Labels: chore

#424 [tofu-derivation] Narrow scope to unimplemented methods only
  derivation/src/test/scala/tofu/higherKind/derived/RepresentableKSuite.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
Labels: fix, hacktoberfest

#415 Streams syntax refactoring
  streams/src/main/scala/tofu/syntax/streams/broadcast.scala
  streams/src/main/scala/tofu/syntax/streams/chunks.scala
  streams/src/main/scala/tofu/syntax/streams/combineK.scala
  streams/src/main/scala/tofu/syntax/streams/compile.scala
  streams/src/main/scala/tofu/syntax/streams/emits.scala
  streams/src/main/scala/tofu/syntax/streams/evals.scala
  streams/src/main/scala/tofu/syntax/streams/filter.scala
  streams/src/main/scala/tofu/syntax/streams/merge.scala
  streams/src/main/scala/tofu/syntax/streams/pace.scala
  streams/src/main/scala/tofu/syntax/streams/package.scala
  streams/src/main/scala/tofu/syntax/streams/parFlatten.scala
  streams/src/main/scala/tofu/syntax/streams/region.scala
  streams/src/main/scala/tofu/syntax/streams/temporal.scala
Labels: hacktoberfest
