Repository tofu-tf/tofu, pull requests merged in 2020-07, with the labels that each got.

#332 Update zio to 1.0.0-RC21-2
  project/Dependencies.scala
Labels: chore

#329 Update sbt to 1.3.13
  project/build.properties
Labels: chore

#327 add timeout docs
  docs/timeout.md
  website/sidebars.json
Labels: docs

#331 new Optic: Grated \ Zipping
  higherKindCore/src/main/scala-2.12/tofu/compat/package.scala
  optics/core/src/main/scala/tofu/optics/Applied.scala
  optics/core/src/main/scala/tofu/optics/Contains.scala
  optics/core/src/main/scala/tofu/optics/Downcast.scala
  optics/core/src/main/scala/tofu/optics/Equivalent.scala
  optics/core/src/main/scala/tofu/optics/Extract.scala
  optics/core/src/main/scala/tofu/optics/Folded.scala
  optics/core/src/main/scala/tofu/optics/Items.scala
  optics/core/src/main/scala/tofu/optics/PBase.scala
  optics/core/src/main/scala/tofu/optics/Property.scala
  optics/core/src/main/scala/tofu/optics/Reduced.scala
  optics/core/src/main/scala/tofu/optics/Repeated.scala
  optics/core/src/main/scala/tofu/optics/Same.scala
  optics/core/src/main/scala/tofu/optics/Subset.scala
  optics/core/src/main/scala/tofu/optics/Upcast.scala
  optics/core/src/main/scala/tofu/optics/Update.scala
  optics/core/src/main/scala/tofu/optics/Zipping.scala
  optics/core/src/main/scala/tofu/optics/classes/Delayed.scala
  optics/core/src/main/scala/tofu/optics/classic.scala
  optics/core/src/main/scala/tofu/optics/data/Constant.scala
  optics/core/src/main/scala/tofu/optics/data/Tagged.scala
  optics/core/src/main/scala/tofu/optics/data/instances.scala
  optics/core/src/main/scala/tofu/optics/data/package.scala
  optics/core/src/main/scala/tofu/optics/optics.scala
  optics/core/src/main/scala/tofu/optics/package.scala
  optics/core/src/test/scala/tofu/optics/core/ChainSuite.scala
  optics/interop/src/main/scala/tofu/optics/interop.scala
  optics/macro/src/main/scala/tofu/optics/macros/GenEquivalent.scala
Labels: enhancement

#333 Upgrade scalafmt to 2.6.1
  .scalafmt.conf
  concurrent/src/main/scala/tofu/concurrent/Agent.scala
  concurrent/src/main/scala/tofu/concurrent/ContextT.scala
  concurrent/src/main/scala/tofu/concurrent/Daemon.scala
  concurrent/src/main/scala/tofu/concurrent/ReadWrite.scala
  config/src/main/scala/tofu/config/Configurable.scala
  core/src/main/scala/tofu/Guarantee.scala
  core/src/main/scala/tofu/common/time.scala
  core/src/main/scala/tofu/control/ApplicativeZip.scala
  core/src/main/scala/tofu/internal/NonTofu.scala
  core/src/main/scala/tofu/lift/Unlift.scala
  core/src/main/scala/tofu/streaming.scala
  core/src/main/scala/tofu/syntax/time.scala
  data/src/main/scala/tofu/data/Calc.scala
  data/src/main/scala/tofu/data/calc/StepResult.scala
  derivation/src/main/scala/tofu/data/derived/ContextEmbed.scala
  env/src/main/scala/tofu/env/Env.scala
  env/src/main/scala/tofu/env/bio/EnvBio.scala
  env/src/main/scala/tofu/env/bio/EnvBioFunctions.scala
  higherKindCore/src/main/scala/tofu/higherKind/Point.scala
  higherKindCore/src/main/scala/tofu/higherKind/RepresentableK.scala
  higherKindCore/src/main/scala/tofu/syntax/functionK.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/annotations.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/show.scala
  logging/structured/src/main/scala/tofu/logging/LogRenderer.scala
  logging/structured/src/main/scala/tofu/logging/Loggable.scala
  logging/structured/src/main/scala/tofu/logging/Logging.scala
  logging/structured/src/main/scala/tofu/logging/Logs.scala
  optics/core/src/main/scala/tofu/optics/Folded.scala
  optics/core/src/main/scala/tofu/optics/Property.scala
  optics/core/src/main/scala/tofu/optics/Update.scala
  optics/core/src/main/scala/tofu/optics/package.scala
  optics/macro/src/main/scala/tofu/optics/macros/internal/Macro.scala
Labels: chore
