Repository tofu-tf/tofu, pull requests merged in 2020-05, with the labels that each got.

#252 Update scalatest to 3.1.2
  project/Dependencies.scala
Labels: chore

#248 Update enumeratum to 1.6.0
  project/Dependencies.scala
Labels: chore

#245 Update monix to 3.2.1
  project/Dependencies.scala
Labels: chore

#84 WIP Bifunctor Env alternative
  env/src/main/scala/tofu/env/Env.scala
  env/src/main/scala/tofu/env/bio/EnvBio.scala
  env/src/main/scala/tofu/env/bio/EnvBioFunctions.scala
  env/src/main/scala/tofu/env/bio/EnvBioProducts.scala
  env/src/main/scala/tofu/env/bio/EnvBioSpecializedFunctions.scala
  env/src/test/scala/tofu/env/bio/EnvBioSuite.scala
Labels: enhancement, wip

#255 Timeout avoid composing with fallback in the Timeout implementation
  concurrent/src/main/scala/tofu/concurrent/Atom.scala
  core/src/main/scala/tofu/Timeout.scala
  core/src/test/scala/tofu/TimeoutChecks.scala
  env/src/main/scala/tofu/env/Env.scala
  env/src/main/scala/tofu/env/EnvInstances.scala
  zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
Labels: fix

#266 Update enumeratum to 1.6.1
  project/Dependencies.scala
Labels: chore

#268 Support simple time and date operations
  build.sbt
  core/src/main/scala/tofu/common/time.scala
  core/src/main/scala/tofu/package.scala
  core/src/main/scala/tofu/syntax/time.scala
  zio/core/src/main/scala/tofu/zioOptics.scala
Labels: enhancement

#271 Upgrade zio to RC-19
  project/Dependencies.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
  zio/logging/src/main/scala/tofu/logging/zlogs/ZLogs.scala
  zio/logging/src/main/scala/tofu/logging/zlogs/ZioHasBuilder.scala
Labels: chore

#237 new import-less alias for Monad
  core/src/main/scala-2.12/tofu/alias/ScalaSpecificDoMonadInstances.scala
  core/src/main/scala-2.13/tofu/alias/ScalaSpecificDoMonadInstances.scala
  core/src/main/scala/tofu/alias/Do.scala
  core/src/main/scala/tofu/alias/package.scala
  core/src/test/scala/examples/DoMonadExamples.scala
Labels: enhancement

#280 Update zio to 1.0.0-RC20
  project/Dependencies.scala
Labels: chore

#286 Fix compiler warnings
  build.sbt
  concurrent/src/test/scala/tofu/concurrent/ReadWriteTests.scala
  config/src/main/scala/tofu/config/typesafe.scala
  core/src/main/scala-2.12/tofu/alias/ScalaSpecificDoMonadInstances.scala
  core/src/main/scala/tofu/Fire.scala
  core/src/main/scala/tofu/alias/Do.scala
  core/src/main/scala/tofu/common/time.scala
  core/src/main/scala/tofu/internal/NonTofu.scala
  core/src/test/scala-2.12/tofu/syntax/FoldableSuite.scala
  core/src/test/scala-2.13/tofu.syntax/FoldableSuite.scala
  core/src/test/scala/examples/DoMonadExamples.scala
  data/src/main/scala/tofu/data/PArray.scala
  env/src/main/scala/tofu/env/EnvRacing.scala
  env/src/main/scala/tofu/env/EnvSpecializedFunctions.scala
  env/src/main/scala/tofu/env/EnvTraversing.scala
  env/src/main/scala/tofu/env/bio/EnvBio.scala
  env/src/test/scala/tofu/env/bio/EnvBioSuite.scala
  higherKindCore/src/main/scala-2.12/tofu/compat/package.scala
  higherKindCore/src/main/scala-2.13/tofu/compat/package.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/package.scala
  logging/structured/src/main/scala/tofu/logging/LogRenderer.scala
  logging/structured/src/main/scala/tofu/logging/Loggable.scala
  logging/structured/src/main/scala/tofu/logging/impl/ContextMarker.scala
  logging/structured/src/main/scala/tofu/syntax/loggable.scala
  optics/core/src/main/scala/tofu/optics/Upcast.scala
  optics/core/src/main/scala/tofu/optics/functions.scala
  project/Dependencies.scala
  zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
Labels: chore, fix

#287 Add Atom implementation for StateT
  concurrent/src/main/scala/tofu/concurrent/Atom.scala
Labels: enhancement
