Repository tofu-tf/tofu, pull requests merged in 2020-09, with the labels that each got.

#375 Update all deps, fix issues
  .scalafmt.conf
  build.sbt
  concurrent/src/main/scala/tofu/concurrent/Daemon.scala
  concurrent/src/main/scala/tofu/concurrent/MakeMVar.scala
  concurrent/src/main/scala/tofu/concurrent/QVar.scala
  concurrent/src/main/scala/tofu/concurrent/ReadWrite.scala
  concurrent/src/main/scala/tofu/concurrent/impl/FocusedRef.scala
  concurrent/src/test/scala/tofu/concurrent/ReadWriteTests.scala
  config/src/main/scala/tofu/config/Configurable.scala
  core/src/main/scala-2.12/tofu/alias/ScalaSpecificDoMonadInstances.scala
  core/src/main/scala-2.13/tofu/alias/ScalaSpecificDoMonadInstances.scala
  core/src/main/scala/tofu/Guarantee.scala
  core/src/main/scala/tofu/alias/Do.scala
  core/src/main/scala/tofu/syntax/bracket.scala
  core/src/main/scala/tofu/syntax/lift.scala
  core/src/main/scala/tofu/syntax/monadError.scala
  data/src/main/scala/tofu/data/Flux.scala
  data/src/test/scala/tofu/data/CalcSuite.scala
  env/src/test/scala/tofu/env/EnvSuite.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
  memo/src/main/scala/tofu/memo/CacheKeyState.scala
  memo/src/main/scala/tofu/memo/CacheState.scala
  memo/src/main/scala/tofu/memo/Memoize.scala
  optics/macro/src/main/scala/tofu/optics/macros/GenEquivalent.scala
  optics/macro/src/main/scala/tofu/optics/macros/Optics.scala
  project/Dependencies.scala
  project/plugins.sbt
  zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
Labels: chore

#374 [tofu-doobie] Relax constraints in ELH.embed
  doobie/src/main/scala/tofu/doobie/log/EmbeddableLogHandler.scala
Labels: fix

#371 Fix Unlift instance ambiguity
  core/src/main/scala/tofu/lift/Unlift.scala
  core/src/test/scala/tofu/lift/UnliftSuite.scala
Labels: fix

#390 Update refined to 0.9.16
  project/Dependencies.scala
Labels: chore

#396 Update refined to 0.9.17
  project/Dependencies.scala
Labels: chore

#399 Update scalafmt-core to 2.7.3
  .scalafmt.conf
Labels: chore

#397 Named composition
  optics/core/src/main/scala/tofu/optics/Contains.scala
  optics/core/src/main/scala/tofu/optics/Downcast.scala
  optics/core/src/main/scala/tofu/optics/Equivalent.scala
  optics/core/src/main/scala/tofu/optics/Extract.scala
  optics/core/src/main/scala/tofu/optics/Folded.scala
  optics/core/src/main/scala/tofu/optics/Items.scala
  optics/core/src/main/scala/tofu/optics/PBase.scala
  optics/core/src/main/scala/tofu/optics/Property.scala
  optics/core/src/main/scala/tofu/optics/Reduced.scala
  optics/core/src/main/scala/tofu/optics/Repeated.scala
  optics/core/src/main/scala/tofu/optics/Same.scala
  optics/core/src/main/scala/tofu/optics/Subset.scala
  optics/core/src/main/scala/tofu/optics/Upcast.scala
  optics/core/src/main/scala/tofu/optics/Update.scala
  optics/core/src/main/scala/tofu/optics/Zipping.scala
  optics/macro/src/main/scala/tofu/optics/macros/GenEquivalent.scala
  optics/macro/src/main/scala/tofu/optics/macros/GenSubset.scala
  optics/macro/src/main/scala/tofu/optics/macros/internal/Macro.scala
  optics/macro/src/test/scala/tofu/optics/macros/GenContainsSpec.scala
  optics/macro/src/test/scala/tofu/optics/macros/GenEquivalentSpec.scala
  optics/macro/src/test/scala/tofu/optics/macros/GenSubsetSpec.scala
  optics/macro/src/test/scala/tofu/optics/macros/TestDomain.scala
Labels: enhancement
