Repository tofu-tf/tofu, pull requests merged in 2021-03, with the labels that each got.

#534 Update tethys-core, tethys-jackson to 0.23.0
  project/Dependencies.scala
Labels: chore

#549 Update sbt-sonatype to 3.9.5
  project/plugins.sbt
Labels: chore

#548 Update sbt-scalafmt to 2.3.4
  project/plugins.sbt
Labels: chore

#547 Update sbt-mdoc to 2.2.18
  project/plugins.sbt
Labels: chore

#546 Update sbt-tpolecat to 0.1.16
  project/plugins.sbt
Labels: chore

#545 Update sbt-updates to 0.5.2
  project/plugins.sbt
Labels: chore

#543 Update sbt-pgp to 2.0.2
  project/plugins.sbt
Labels: chore

#542 Update sbt-unidoc to 0.4.3
  project/plugins.sbt
Labels: chore

#541 Update sbt-scalafix to 0.9.26
  project/plugins.sbt
Labels: chore

#544 Update sbt-rewarn to 0.1.3
  project/plugins.sbt
Labels: chore

#556 Update sbt to 1.4.9
  project/build.properties
Labels: chore

#554 Update zio to 1.0.5
  project/Dependencies.scala
Labels: chore

#553 Update scalatest to 3.2.6
  project/Dependencies.scala
Labels: chore

#551 Update sbt-scalafmt to 2.4.2
  project/plugins.sbt
Labels: chore

#550 Update sbt-pgp to 2.1.1
  project/plugins.sbt
Labels: chore

#555 Update doobie-core to 0.12.0
  project/Dependencies.scala
Labels: chore

#557 Update sbt-pgp to 2.1.2
  project/plugins.sbt
Labels: chore

#559 Update sbt-sonatype to 3.9.6
  project/plugins.sbt
Labels: chore

#560 Update sbt-sonatype to 3.9.7
  project/plugins.sbt
Labels: chore

#561 FindRaise in feither, foption, timeout syntax
  core/src/main/scala/tofu/syntax/error.scala
  core/src/main/scala/tofu/syntax/feither.scala
  core/src/main/scala/tofu/syntax/foption.scala
  core/src/main/scala/tofu/syntax/timeout.scala
  core/src/test/scala/tofu/syntax/FindRaiseSuite.scala
Labels: fix

#568 Update derevo-cats-tagless, derevo-core to 0.12.2
  project/Dependencies.scala
Labels: dependencies

#567 Factorize and cooler Logs
  .scalafix.conf
  build.sbt
  config/src/main/scala/tofu/config/typesafe.scala
  core/src/main/scala/tofu/Delay.scala
  core/src/main/scala/tofu/bi/BiContext.scala
  core/src/main/scala/tofu/bi/package.scala
  data/src/main/scala/tofu/data/Embedded.scala
  data/src/main/scala/tofu/data/calc/CalcMInstances.scala
  derivation/src/main/scala/tofu/data/derived/ContextEmbed.scala
  derivation/src/main/scala/tofu/data/derived/package.scala
  derivation/src/main/scala/tofu/higherKind/derived/ContextEmbed.scala
  env/src/main/scala/tofu/env/bio/EnvBioInstances.scala
  env/src/main/scala/tofu/env/bio/package.scala
  higherKindCore/src/main/scala/tofu/control/Bind.scala
  higherKindCore/src/main/scala/tofu/control/impl/BindInstanceChain.scala
  higherKindCore/src/main/scala/tofu/higherKind/FunctionHK.scala
  higherKindCore/src/main/scala/tofu/higherKind/Mid.scala
  higherKindCore/src/main/scala/tofu/higherKind/Point.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/BiMid.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/BiPoint.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/MonoidBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/SemigroupBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/extensions.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
  higherKindCore/src/main/scala/tofu/higherKind/derived/derived.scala
  higherKindCore/src/main/scala/tofu/syntax/bind.scala
  higherKindCore/src/main/scala/tofu/syntax/functorbk.scala
  higherKindCore/src/main/scala/tofu/syntax/monoidalK.scala
  higherKindCore/src/test/scala/tofu/higherKind/FactorizeSuite.scala
  logging/derivation/src/main/scala/tofu/logging/derivation/loggingMid.scala
  logging/derivation/src/test/scala/tofu/logging/derivation/LoggingMidSuite.scala
  logging/structured/src/main/scala/tofu/logging/Loggable.scala
  logging/structured/src/main/scala/tofu/logging/LoggableInstances.scala
  logging/structured/src/main/scala/tofu/logging/LoggedValue.scala
  logging/structured/src/main/scala/tofu/logging/Logging.scala
  logging/structured/src/main/scala/tofu/logging/LoggingCompanion.scala
  logging/structured/src/main/scala/tofu/logging/LoggingMid.scala
  logging/structured/src/main/scala/tofu/logging/Logs.scala
  logging/structured/src/main/scala/tofu/logging/bi/LoggingBiCompanion.scala
  logging/structured/src/main/scala/tofu/logging/bi/LoggingBiMid.scala
  logging/structured/src/main/scala/tofu/logging/builder/LoggingBiMidBuilder.scala
  logging/structured/src/main/scala/tofu/logging/builder/LoggingMidBuilder.scala
  logging/structured/src/main/scala/tofu/logging/impl/ArgsLoggable.scala
  logging/structured/src/main/scala/tofu/logging/impl/CachedLogs.scala
  logging/structured/src/main/scala/tofu/logging/impl/LoggingMidFunctions.scala
  logging/structured/src/main/scala/tofu/logging/impl/UniversalEmbedLogs.scala
  logging/structured/src/main/scala/tofu/logging/impl/UniversalLogging.scala
  logging/structured/src/test/scala/tofu/logging/LoggingSuite.scala
  logging/util/src/main/scala/tofu/logging/atom/AtomLogger.scala
  optics/core/src/main/scala/tofu/optics/Downcast.scala
  optics/core/src/main/scala/tofu/optics/Extract.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
  zio/logging/src/main/scala/tofu/logging/zlogs/ZLogs.scala
Labels: enhancement

#582 Update log4cats-core to 2.0.0
  project/Dependencies.scala
Labels: chore

#581 Update cats-mtl to 1.1.3
  project/Dependencies.scala
Labels: chore

#580 Update cats-effect to 2.4.1
  project/Dependencies.scala
Labels: chore

#579 Update scala-collection-compat to 2.4.3
  project/Dependencies.scala
Labels: chore

#576 Update sbt-mdoc to 2.2.19
  project/plugins.sbt
Labels: chore

#575 Update zio-interop-cats to 2.4.0.0
  project/Dependencies.scala
Labels: chore

#573 Update sbt-scalafix to 0.9.27
  project/plugins.sbt
Labels: chore
