Repository tofu-tf/tofu, pull requests merged in 2021-02, with the labels that each got.

#495 Update scala-collection-compat to 2.4.1
  project/Dependencies.scala
Labels: chore

#496 Update sbt to 1.4.7
  project/build.properties
Labels: chore

#497 Update zio to 1.0.4-1
  project/Dependencies.scala
Labels: chore

#498 Update zio to 1.0.4-2
  project/Dependencies.scala
Labels: chore

#502 Update tethys-core, tethys-jackson to 0.21.0
  project/Dependencies.scala
Labels: chore

#504 Update alleycats-core, cats-core, cats-free to 2.4.0
  concurrent/src/main/scala/tofu/concurrent/impl/contextt.scala
  core/src/main/scala/tofu/control/impl/SelectiveInstances.scala
  optics/core/src/main/scala/tofu/optics/Contains.scala
  project/Dependencies.scala
Labels: chore

#518 Update cats-effect to 2.3.2
  project/Dependencies.scala
Labels: chore

#517 Update alleycats-core, cats-core, cats-free to 2.4.2
  project/Dependencies.scala
Labels: chore

#516 Update scala-collection-compat to 2.4.2
  project/Dependencies.scala
Labels: chore

#526 Update fs2-io to 2.5.2
  project/Dependencies.scala
Labels: chore

#525 Update refined to 0.9.21
  project/Dependencies.scala
Labels: chore

#524 Update scalatest to 3.2.4
  project/Dependencies.scala
Labels: chore

#527 Improve Txr usability
  doobie/src/main/scala/tofu/doobie/transactor/Txr.scala
  doobie/src/main/scala/tofu/syntax/doobie/package.scala
  doobie/src/main/scala/tofu/syntax/doobie/txr.scala
  doobie/src/test/scala/tofu/doobie/TxrSuite.scala
  doobie/src/test/scala/tofu/doobie/example/TofuDoobieExample.scala
Labels: enhancement

#528 Update scalatest to 3.2.5
  project/Dependencies.scala
Labels: chore

#529 Update fs2-io to 2.5.3
  project/Dependencies.scala
Labels: chore

#531 Update README
  README.md
Labels: docs
