Repository tofu-tf/tofu, pull requests merged in 2021-04, with the labels that each got.

#590 Update sbt to 1.5.0
  project/build.properties
Labels: chore

#589 Update refined to 0.9.23
  project/Dependencies.scala
Labels: chore

#587 Update log4cats-core to 1.2.2
  project/Dependencies.scala
Labels: chore

#586 Update scalatest to 3.2.7
  project/Dependencies.scala
Labels: chore

#596 Drop sbt-0.13.x syntax
  build.sbt
Labels: chore

#606 Cleanup macros for HK derivation
  higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
Labels: enhancement

#602 Added useful things and test for bifunctor mid log
  build.sbt
  derivation/src/main/scala/tofu/higherKind/derived/derived.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/BiTemplate.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/FunctorBK.scala
  higherKindCore/src/main/scala/tofu/higherKind/bi/RepBK.scala
  higherKindCore/src/main/scala/tofu/syntax/functorbk.scala
  logging/structured/src/main/scala/tofu/logging/LoggableInstances.scala
  logging/structured/src/main/scala/tofu/logging/Logs.scala
  logging/structured/src/main/scala/tofu/logging/builder/LoggingBiMidBuilder.scala
  zio/core/src/main/scala/tofu/zioFunctions.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioInstances.scala
  zio/core/src/main/scala/tofu/zioInstances/ZioTofuBiInstance.scala
  zio/core/src/main/scala/tofu/zioInstances/implicits.scala
  zio/logging/src/main/scala/tofu/logging/zlogs/package.scala
  zio/logging/src/test/scala/tofu/logging/zlogs/ZLogBiMidSuite.scala
  zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
  zio/logging/src/test/scala/tofu/logging/zlogs/ZTestLog.scala
Labels: enhancement

#609 Update alleycats-core, cats-core, cats-free to 2.6.0
  project/Dependencies.scala
Labels: chore

#608 Update doobie-core to 0.13.0
  project/Dependencies.scala
Labels: chore

#610 Update cats-effect to 2.5.0
  project/Dependencies.scala
Labels: chore

#611 Update cats-mtl to 1.2.0
  project/Dependencies.scala
Labels: chore

#612 Update sbt-mdoc to 2.2.20
  project/plugins.sbt
Labels: chore

#613 Update zio-interop-cats to 2.4.1.0
  project/Dependencies.scala
Labels: chore

#614 Update scalatest to 3.2.8
  project/Dependencies.scala
Labels: chore

#615 Update refined to 0.9.24
  project/Dependencies.scala
Labels: chore

#618 Update zio to 1.0.7
  project/Dependencies.scala
Labels: chore

#619 Update fs2-io to 2.5.5
  project/Dependencies.scala
Labels: chore

#620 Update log4cats-core to 1.3.0
  project/Dependencies.scala
Labels: chore

#622 Update doobie-core to 0.13.1
  project/Dependencies.scala
Labels: chore

#621 Update sbt to 1.5.1
  project/build.properties
Labels: chore

#625 Update derevo-cats-tagless, derevo-core to 0.12.5
  project/Dependencies.scala
Labels: chore

#626 Release 0.10.2
  build.sbt
Labels: skip-changelog
