Repository tofu-tf/tofu, pull requests merged in 2021-05, with the labels that each got.

#627 Update release-drafter.yml
  .github/release-drafter.yml
Labels: skip-changelog

#628 Update shapeless to 2.3.5
  project/Dependencies.scala
Labels: dependencies

#644 Update shapeless to 2.3.7
  project/Dependencies.scala
Labels: chore

#643 Update kind-projector to 0.13.0
  project/Dependencies.scala
Labels: chore

#642 Update scalatest to 3.2.9
  project/Dependencies.scala
Labels: chore

#641 Update sbt-mdoc to 2.2.21
  project/plugins.sbt
Labels: chore

#640 Update refined to 0.9.25
  project/Dependencies.scala
Labels: chore

#639 Update fs2-io to 2.5.6
  project/Dependencies.scala
Labels: chore

#638 Update scala-collection-compat to 2.4.4
  project/Dependencies.scala
Labels: chore

#637 Update monix to 3.4.0
  project/Dependencies.scala
Labels: chore

#636 Update cats-mtl to 1.2.1
  project/Dependencies.scala
Labels: chore

#635 Update cats-effect to 2.5.1
  project/Dependencies.scala
Labels: chore

#634 Update alleycats-core, cats-core, cats-free to 2.6.1
  project/Dependencies.scala
Labels: chore

#631 Update sbt to 1.5.2
  project/build.properties
Labels: chore

#629 Update doobie-core to 0.13.2
  project/Dependencies.scala
Labels: chore

#648 Update zio to 1.0.8
  project/Dependencies.scala
Labels: chore

#647 Update doobie-core to 0.13.3
  project/Dependencies.scala
Labels: chore

#646 Update log4cats-core to 1.3.1
  project/Dependencies.scala
Labels: chore

#645 Update scala-library, scala-reflect to 2.13.6
  .github/workflows/scala.yml
  project/Dependencies.scala
Labels: chore

#649 Update zio-interop-cats to 2.5.1.0
  project/Dependencies.scala
Labels: chore

#652 Update sbt-git to 1.0.1
  project/plugins.sbt
Labels: chore

#654 Update doobie-core to 0.13.4
  project/Dependencies.scala
Labels: chore

#656 Update refined to 0.9.26
  project/Dependencies.scala
Labels: chore

#657 Update circe-core to 0.14.1
  project/Dependencies.scala
Labels: chore

#658 Update sbt-tpolecat to 0.1.19
  project/plugins.sbt
Labels: chore

#659 Update tethys-core, tethys-jackson to 0.24.0
  project/Dependencies.scala
Labels: chore

#660 Update scala-library, scala-reflect to 2.12.14
  .github/workflows/scala.yml
  project/Dependencies.scala
Labels: chore
