Repository tofu-tf/tofu, pull requests merged in 2021-09, with the labels that each got.

#746 Update mdoc, sbt-mdoc to 2.2.23
  project/plugins.sbt
Labels: dependency-update

#745 Update kind-projector to 0.13.1
  project/Dependencies.scala
Labels: dependency-update

#744 Update sbt-sonatype to 3.9.10
  project/plugins.sbt
Labels: dependency-update

#749 Update kind-projector to 0.13.2
  project/Dependencies.scala
Labels: dependency-update

#751 Update logback-classic to 1.2.6
  project/Dependencies.scala
Labels: dependency-update

#750 Update groovy to 3.0.9
  project/Dependencies.scala
Labels: dependency-update

#754 Update http4s-blaze-server, http4s-circe, ... to 0.22.4
  project/Dependencies.scala
Labels: dependency-update

#757 Exclude http4s from .scala-steward.conf
  .scala-steward.conf
Labels: skip-changelog

#760 Update scala-library, scala-reflect to 2.12.15
  .github/workflows/ci.yml
  project/Dependencies.scala
Labels: dependency-update

#763 Update tethys-core, tethys-jackson to 0.25.0
  project/Dependencies.scala
Labels: dependency-update

#765 Update sbt-scalafix to 0.9.31
  project/plugins.sbt
Labels: dependency-update

#770 Update scalafmt-core to 3.0.4
  .scalafmt.conf
Labels: dependency-update

#769 fix docs
  build.sbt
  modules/doobie/core/src/main/scala/tofu/doobie/log/EmbeddableLogHandler.scala
  modules/kernel/src/main/scala/tofu/Scoped.scala
  modules/kernel/src/main/scala/tofu/WithContext.scala
  modules/kernel/src/main/scala/tofu/kernel/types.scala
  modules/kernel/src/main/scala/tofu/lift/Unlift.scala
  modules/kernel/src/main/scala/tofu/syntax/scoped.scala
Labels: chore, fix, docs

#781 Update zio to 1.0.12
  project/Dependencies.scala
Labels: dependency-update

#773 Update cats-effect to 2.5.4
  project/Dependencies.scala
Labels: dependency-update

#772 Update scalatest to 3.2.10
  project/Dependencies.scala
Labels: dependency-update

#785 Update sbt-ci-release to 1.5.9
  project/plugins.sbt
Labels: dependency-update

#784 Update http4s-dsl to 0.22.5
  project/Dependencies.scala
Labels: dependency-update

#787 Fix unused warnings in logging
  modules/zio/logging/src/main/scala/tofu/logging/zlogs/ZLogging.scala
  modules/zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
Labels: fix

#788 Update sbt-scoverage to 1.9.0
  project/plugins.sbt
Labels: dependency-update
