Repository tofu-tf/tofu, pull requests merged in 2021-07, with the labels that each got.

#691 Update scala-collection-compat to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#690 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#692 Turn off fatal warnings during publish
  build.sbt
Labels: skip-changelog

#695 Fix module names in build.sbt
  build.sbt
  modules/concurrent/src/test/scala/tofu/concurrent/ContextTRebaseSuite.scala
Labels: chore, skip-changelog

#699 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#696 Update fs2-io to 2.5.9
  project/Dependencies.scala
Labels: dependency-update

#697 Drop build rework leftovers
  .publish.xml
  streams/src/main/scala-2.12/tofu/streams/internal/package.scala
  streams/src/main/scala-2.13/tofu/streams/internal/package.scala
  streams/src/main/scala/tofu/streams/Broadcast.scala
  streams/src/main/scala/tofu/streams/Chunks.scala
  streams/src/main/scala/tofu/streams/Compile.scala
  streams/src/main/scala/tofu/streams/Emits.scala
  streams/src/main/scala/tofu/streams/Merge.scala
  streams/src/main/scala/tofu/streams/Pace.scala
  streams/src/main/scala/tofu/streams/ParFlatten.scala
  streams/src/main/scala/tofu/streams/Region.scala
  streams/src/main/scala/tofu/streams/Temporal.scala
  streams/src/main/scala/tofu/syntax/streams/broadcast.scala
  streams/src/main/scala/tofu/syntax/streams/chunks.scala
  streams/src/main/scala/tofu/syntax/streams/combineK.scala
  streams/src/main/scala/tofu/syntax/streams/compile.scala
  streams/src/main/scala/tofu/syntax/streams/emits.scala
  streams/src/main/scala/tofu/syntax/streams/evals.scala
  streams/src/main/scala/tofu/syntax/streams/filter.scala
  streams/src/main/scala/tofu/syntax/streams/merge.scala
  streams/src/main/scala/tofu/syntax/streams/pace.scala
  streams/src/main/scala/tofu/syntax/streams/package.scala
  streams/src/main/scala/tofu/syntax/streams/parFlatten.scala
  streams/src/main/scala/tofu/syntax/streams/region.scala
  streams/src/main/scala/tofu/syntax/streams/temporal.scala
  streams/src/test/scala/tofu/streams/SyntaxTypeInferenceSuite.scala
Labels: skip-changelog

#693 [Config] Allow simple types to be parsed from strings
  modules/config/src/main/scala/tofu/config/ConfigItem.scala
  modules/config/src/main/scala/tofu/config/Configurable.scala
  modules/config/src/test/resources/suite.conf
  modules/config/src/test/scala/tofu/config/ConfigSuite.scala
Labels: enhancement

#694 [ZIO] Unlift Part of big Has Context
  modules/zio/core/src/main/scala/tofu/zioInstances/ZioInstances.scala
  modules/zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
Labels: enhancement

#698 Continuational representation of ConnectionIO
  modules/doobie/src/main/scala-2.12/tofu/doobie/instances/DoobieImplicitsScalaVersionSpecific.scala
  modules/doobie/src/main/scala-2.13/tofu/doobie/instances/DoobieImplicitsScalaVersionSpecific.scala
  modules/doobie/src/main/scala/tofu/doobie/ConnectionCIO.scala
  modules/doobie/src/main/scala/tofu/doobie/instances/DoobieInstances.scala
  modules/doobie/src/main/scala/tofu/doobie/instances/implicits.scala
  modules/doobie/src/main/scala/tofu/doobie/package.scala
  modules/doobie/src/main/scala/tofu/doobie/transactor/Txr.scala
  modules/doobie/src/main/scala/tofu/syntax/doobie/txr.scala
  modules/doobie/src/test/scala/tofu/doobie/DoobieInstancesSuite.scala
  modules/doobie/src/test/scala/tofu/doobie/TxrSuite.scala
  modules/doobie/src/test/scala/tofu/doobie/example/TofuDoobieExample.scala
  modules/kernel/src/main/scala/tofu/internal/ContextBase.scala
  modules/kernel/src/test/scala/tofu/ContextSummonSuite.scala
Labels: enhancement

#712 Add CalcM.tailrecEither
  modules/kernel/src/main/scala/tofu/data/calc/CalcMOps.scala
Labels: enhancement

#713 lower priority of zioTofuErrorsToInstance
  modules/zio/core/src/main/scala/tofu/zioInstances/implicits.scala
  modules/zio/core/src/test/scala/tofu/zioInstances/ZioInstancesSuite.scala
Labels: fix

#709 Kernelize Atom and QVar
  modules/core/src/test/scala/tofu/concurrent/AtomSuite.scala
  modules/core/src/test/scala/tofu/concurrent/QVarSuite.scala
  modules/kernel/src/main/scala/tofu/concurrent/Atom.scala
  modules/kernel/src/main/scala/tofu/concurrent/QVar.scala
  modules/kernel/src/main/scala/tofu/internal/ContextBase.scala
  modules/kernel/src/main/scala/tofu/internal/Interop.scala
  modules/kernel/src/main/scala/tofu/internal/carriers/FibersCarrier.scala
  modules/kernel/src/main/scala/tofu/internal/carriers/FinallyCarrier.scala
  modules/kernel/src/main/scala/tofu/internal/carriers/UnliftCarrier.scala
  modules/kernel/src/main/scala/tofu/internal/carriers/UnliftEffect.scala
  modules/kernel/src/main/scala/tofu/internal/carriers/concurrent.scala
  modules/kernelCE2Interop/src/main/scala/tofu/interop/AtomByRef.scala
  modules/kernelCE2Interop/src/main/scala/tofu/interop/CE2Kernel.scala
  modules/kernelCE2Interop/src/main/scala/tofu/interop/QVarByMVar.scala
Labels: breaking-change

#714 Update logback-classic to 1.2.4
  project/Dependencies.scala
Labels: dependency-update

#715 Update refined to 0.9.27
  project/Dependencies.scala
Labels: dependency-update

#717 Update slf4j-api to 1.7.32
  project/Dependencies.scala
Labels: dependency-update

#721 Update mdoc, sbt-mdoc to 2.2.22
  project/plugins.sbt
Labels: dependency-update

#723 Add collections and parallel syntax
  modules/core/src/test/scala-2.13/tofu.syntax/FoldableSuite.scala
  modules/higherKindCore/src/main/scala/tofu/syntax/monadic.scala
  modules/kernel/src/main/scala/tofu/syntax/collections.scala
  modules/kernel/src/main/scala/tofu/syntax/foldable.scala
  modules/kernel/src/main/scala/tofu/syntax/parallel.scala
  modules/kernel/src/main/scala/tofu/syntax/traverse.scala
Labels: enhancement

#722 Fix QVar implementation for MVar-less runtime
  modules/kernel/src/main/scala/tofu/concurrent/impl/QVarSM.scala
  modules/zio/core/src/main/scala/tofu/zioInstances/ZioTofuConcurrentInstance.scala
  modules/zio/core/src/test/scala/tofu/zioInstances/ZioQVarSuite.scala
Labels: fix

#725 Update logback-classic to 1.2.5
  project/Dependencies.scala
Labels: dependency-update

#729 Update cats-effect to 2.5.2
  project/Dependencies.scala
Labels: dependency-update

#728 Update zio to 1.0.10
  project/Dependencies.scala
Labels: dependency-update
