Repository tofu-tf/tofu, pull requests merged in 2022-11, with the labels that each got.

#1032 Introduce LogAnnotation
  docs/tofu.logging.annotation.md
  modules/logging/structured/src/main/scala/tofu/logging/LogAnnotation.scala
  modules/logging/structured/src/main/scala/tofu/logging/Loggable.scala
  website/sidebars.json
Labels: enhancement

#1062 Update sbt-ci-release
  build.sbt
  project/plugins.sbt
Labels: chore, dependency-update

#1061 Update scala 2.12 and scalatest
  .github/workflows/ci.yml
  project/Dependencies.scala
Labels: chore, dependency-update

#1063 update fs2 (CE3)
  examples-ce3/src/main/scala/tofu/example/doobie/TofuDoobieExample.scala
  project/Dependencies.scala
Labels: fix, dependency-update
